"""
GPT Client Module

This module implements the GPT client adapter that communicates with the OpenAI API
using LangChain. It sends the composed prompt to the language model and returns the
generated response as a BotResponse object.
"""

from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from langchain_openai import ChatOpenAI

from adapters.loggers.logger_adapter import app_logger
from config import Config
from core.domain.dialog_model import BotResponse
from core.interfaces.openai_gpt_client_interface import IOpenGPTClient


class OpenAIGPTClient(IOpenGPTClient):
    """
    Concrete implementation of the IOpenGPTClient interface for OpenAI's GPT using LangChain.
    """

    def __init__(self):
        self.api_key = Config.OPENAI_API_KEY
        app_logger.info("OpenAIGPTClient initialized with API key from config.")

        self.llm = ChatOpenAI(
            temperature=0.7,
            model_name="gpt-4o",
            api_key=self.api_key
        )

        prompt_template = PromptTemplate(
            input_variables=["prompt"], template="{prompt}"
        )

        self.chain = LLMChain(llm=self.llm, prompt=prompt_template)
        app_logger.info("LangChain LLMChain created successfully.")

    def generate_text(self, prompt: str) -> BotResponse:
        """
        Sends the composed prompt to the GPT API via LangChain and returns the generated text
        as a BotResponse.

        Args:
            prompt (str): The prompt to be sent to the language model.

        Returns:
            BotResponse: The response generated by the language model.
        """
        try:
            app_logger.debug("Sending prompt to GPT API via LangChain")
            result = self.chain.run(prompt=prompt)
            result_text = result.strip()
            app_logger.info(
                "Received response from GPT API via LangChain successfully."
            )
            return BotResponse(text=result_text)
        except Exception as e:
            app_logger.error(
                "Error generating text from GPT API via LangChain: %s", str(e)
            )
            raise