"""
GPT Client Module

This module implements the GPT client adapter that communicates with the OpenAI API.
It sends the composed prompt to the language model and returns the generated response
as a BotResponse object.
"""

import os

import openai

from adapters.loggers.logger_adapter import app_logger
from core.domain.dialog_model import BotResponse
from core.interfaces.openai_gpt_client_interface import IOpenGPTClient


class OpenAIGPTClient(IOpenGPTClient):
    """
    Concrete implementation of the IGPTAdapter interface for OpenAI's GPT.
    """

    def __init__(self):
        openai.api_key = os.environ.get("OPENAI_API_KEY", "your-api-key-here")
        app_logger.info("OpenAIGPTClient initialized with provided API key.")

    def generate_text(self, prompt: str) -> BotResponse:
        """
        Sends the prompt to the GPT API and returns the generated text as a BotResponse.

        Args:
            prompt (str): The prompt to be sent to the language model.

        Returns:
            BotResponse: The response generated by the language model.
        """
        try:
            app_logger.debug("Sending prompt to GPT API: %s", prompt)
            response = openai.Completion.create(
                model="text-davinci-003",  # Adjust model
                prompt=prompt,
                max_tokens=100,
                temperature=0.7,
            )
            content = response["choices"][0]["text"].strip()
            app_logger.info("Received response from GPT API successfully.")
            return BotResponse(text=content)
        except Exception as e:
            app_logger.error("Error generating text from GPT API: %s", str(e))
            raise
