services:
  dialog-orchestrator-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dialog-orchestrator-service
    restart: always
    ports:
      - "5002:5002"
    networks:
      - persona_network
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=False
      - LOG_LEVEL=DEBUG
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-change-this-in-production}
      - PERSONA_ENGINE_URL=http://persona-engine-service:5001
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  persona_network:
    external: true
