"""
Open GPT Client Interface Module

This module defines the interface for the OpenGPT client adapter.
Any concrete implementation that communicates with the OpenAI GPT API must implement
the generate_text method to return a BotResponse based on a provided prompt.
"""

from abc import ABC, abstractmethod

from core.domain.dialog_model import BotResponse


class IOpenGPTClient(ABC):
    """
    Interface for the Open GPT Client Adapter.

    This interface specifies the method that any concrete OpenGPT client must implement
    to generate text based on a given prompt. The output should be encapsulated in a BotResponse
    object.
    """

    @abstractmethod
    def generate_text(self, prompt: str) -> BotResponse:
        """
        Generate text using the GPT API with the provided prompt.

        Args:
            prompt (str): The prompt to send to the GPT API.

        Returns:
            BotResponse: The response generated by the GPT API.
        """
        pass
