"""
Dialog Model Module

This module defines the core domain models for the Dialog Orchestrator application.
It encompasses components that generate dialogue from user input and personality data.

The module defines two primary data structures:
    - UserMessage: Represents the user's input message, including a user identifier.
    - BotResponse: Represents the response generated by the LLM based on the composed prompt.

These models serve as the basis for handling dialogue interactions within the system.
"""

from dataclasses import dataclass


@dataclass
class UserMessage:
    """
    Represents a user message in the dialog system.

    Attributes:
        user_id (str): Unique identifier for the user sending the message.
        text (str): The text of the user's message.
    """

    user_id: str
    text: str


@dataclass
class BotResponse:
    """
    Represents the response generated by the system (via LLM) for a given user message.

    Attributes:
        text (str): The text content of the generated bot response.
    """

    text: str
